from connect_four.problem.group import Group
from connect_four.problem.group import GroupDirection

from connect_four.problem.connecting_problem_manager import ConnectingProblemManager
from connect_four.problem.tic_tac_toe_problem_manager import TicTacToeProblemManager
from connect_four.problem.connect_four_problem_manager import ConnectFourProblemManager
